### Analyse output results

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
filename = '../data/output/theta_CRep.npz'
theta = np.load(filename)

In [3]:
u,v,w,eta = theta['u'],theta['v'],theta['w'],theta['eta']

In [4]:
u

array([[0.        , 1.        , 0.        ],
       [0.        , 0.66901078, 0.33098922],
       [0.        , 0.73152525, 0.26847475],
       ...,
       [0.92174939, 0.07825061, 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ]])

In [5]:
v

array([[0.        , 0.68693478, 0.31306522],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       ...,
       [0.        , 0.        , 1.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ]])

In [6]:
w

array([[0.0226852 , 0.02808736, 0.03392388]])

In [7]:
eta

array(0.44088065)